CREATE TABLE FARMTECH_FASE4 (
    id_leitura INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    n_sensor INTEGER,
    p_sensor INTEGER,
    k_sensor INTEGER,
    temperatura NUMBER(10, 2),   
    umidade NUMBER(10, 2),
    ph NUMBER(10, 2),
    chuva NUMBER(10, 2),          
    cultura_label VARCHAR2(50),
    produtividade_estimada NUMBER(10, 2), 
    irrigacao_necessaria NUMBER(10, 2),   
    data_leitura TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);